---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mysql-dev
  namespace: dev
spec:
  releaseName: mysql-dev
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mysql
    version: 1.2.2
